### PR TITLE
Added Custom User & Pass to `docker-compose.yml`

### LINKED ISSUE #115: Update the docker-compose.yml file to include a custom username/password for cassandra
To prepare for a dev environment, we need to add authentication to the CassandraConnector.  This is the first step

### PR DESCRIPTION
**Pull request by Hopding**
Fixes #115. @thebho  is this all you were looking for in #115, or were you looking for something more?

### CODE REVIEW

**Comment by thebho** [comment]
Not doing this until we have the cassandra config fixed

**Comment by Hopding** [comment]
May want to take a look at this again if https://github.com/maryvilledev/skilldirectory/issues/117 is merged.

**Comment by Hopding** [comment]
This PR expands on #116 - which setup `PasswordAuthenticator` logic in the
`CassandraConnector`. This PR sets up the Cassandra database to require all
queries to be authenticated with a valid user and pass. By default, Cassandra
has a single (super)user "preinstalled": user: `cassandra` pass: `cassandra`.
This PR does not add or remove any users. It adds two env vars that are created
in the `make` file and are used for the `cqlsh` commands performed therein.
These vars are passed to the `docker-compose.yml` file so that the `CassandraConnector`
is able to pull them as env vars. All requests sent to the API will then end up
using the default superuser credentials to access the database. Obviously, this
isn't a complete solution, but it sets the groundwork for one.

**Review by thebho — APPROVED** [review]
Nice!

**Pull request merged**
