### PR TITLE
Refact make

### PR DESCRIPTION
**Pull request by thebho**
Closes https://github.com/maryvilledev/skilldirectoryinfra/issues/2

Note:
- This takes the docker commands away from this repo.  CirceCI will still build the image based on the Dockerfile, but running `./make` does a `go run main.go` with a connection to the cassandra container if running.
- Moved cassandra schema and Dockerfile to the infra project.  Any schema changes will need to happen on that project.  Note that I am still manually pushing the cassandra image, will make a story to add Circle to the infra project

Developer Options:
1. Checkout `skilldirectoryinfra` and run `./devstack` to start the entire application
2. Checkout `skilldirectoryinfra` and run `./devstack data` and checkout  `skilldirectory` && `skilldirectoryui`.  Run `./make` here and `npm start` there to compile and run your local code
3. Mix and match with docker containers and your own builds.  We will need to keep an eye urls and ports in case I missed something there.
4. There is also an option to run the UI with the `dev` backend.  can describe that if needed.

### CODE REVIEW

**Comment by solkaz** [comment]
Looks good to me. Does it essentially decouple responsibility of setting up the containers and gives that responsibility to `skilldirectoryinfra`?

**Review by solkaz — APPROVED** [review]

**Review by smokinGun — APPROVED** [review]

**Comment by thebho** [comment]
Correct.  You can still build the image with `docker build -t {tag_name} .` and then change the image name in the docker-compose.yml if you want to test something in docker.  I did that test my changes before pushing. But most of that time that won't be an issue.

**Comment by Hopding** [comment]
So this change is setting up this project (skilldirectory) to be **only** the API and server - not the database as well? The database stuff is now all over in [skilldirectoryinfra](https://github.com/maryvilledev/skilldirectoryinfra)?

**Comment by thebho** [comment]
Correct, @Hopding

**Review by Hopding — APPROVED** [review]

**Review by dane-johnson — APPROVED** [review]
LGTM

**Pull request merged**
