### PR TITLE
Add TMSkills to TeamMember GETs

### LINKED ISSUE #74: When doing a GET on a team member id, return all associated tm_skills
`/team_members` returns all team_members
`/team_members/team_member_id` returns team member with all tm_skills

### PR DESCRIPTION
**Pull request by Hopding**
Fixes #74.

### CODE REVIEW

**Comment by thebho** [comment]
Is this returning the Skill Name with the TMSkill?

**Comment by Hopding** [comment]
It is not. I take it that I should make it do that?

**Comment by Hopding** [comment]
[This PR](https://github.com/maryvilledev/skilldirectory/pull/101) is adding a `TMSkillDTO` that includes a `skill_name` and `team_member_name` for each `TMSkill`. It would be convenient to just reuse that DTO in this PR for showing the `skill_name`. The only potential issue with this would be that you would also get the `team_member_name`. So a GET on a TeamMember might return:
```json
{
    "id": "4b925ede-ceb7-11e6-9566-6c4008bcfa84",
    "name": "Yogi Bear",
    "title": "Smart Than Average Bear",
    "tm_skills":[
      {
        "id": "749322dc-ceb7-11e6-9568-6c4008bcfa84",
        "skill_id": "6b3af8d6-ceb7-11e6-9567-6c4008bcfa84",
        "team_member_id": "4b925ede-ceb7-11e6-9566-6c4008bcfa84",
        "wish_list": false,
        "proficiency": 0,
        "skill_name": "Java",
        "team_member_name": "Yogi Bear"
      }
    ]
  }
```
So you would end up getting the Team Member's name twice. I'm fine with this, and it would make it simpler to implement than trying to avoid the duplicate name. Do you see it as a problem?

**Review by thebho — CHANGES_REQUESTED** [review]
Asked for changes IRL

**Comment by Hopding** [comment]
Should be ready for merge now 👍

**Review by thebho — APPROVED** [review]

**Pull request merged**
