### PR TITLE
Allowed error from unmarshalling to log immediately so malconstructed JSON objects are detected by validation functions

### LINKED ISSUE #189: Change error message for empty POSTS
When doing a post request with empty body, error message is:
```
unexpected end of JSON input

```
This is because the API tries to parse request body as JSON and if it fails it just returns the error created `json.Unmarshal`.

I suggest that if a Unmarshaling error occurs response should be:

```
POST request bodies must contain valid JSON object.
```

### PR DESCRIPTION
**Pull request by dane-johnson**
Closes #189

### CODE REVIEW

**Review by thebho — CHANGES_REQUESTED** [review]
Ignoring the err feels wrong here.  Maybe catch the error, log it, and return a custom response.  You have validateLink catching both JSON and validation errors which is confusing and over complicates what the validate is supposed to be doing.

**Comment by thebho** [comment]
Testing

**Comment by dane-johnson** [comment]
The error is only thrown if the JSON is invalid, which is something that the validate functions are already checking for. I don't see how it is substantially different if it is not a json object or a malformed json object.

**Comment by thebho** [comment]
The validate is there to confirm that the explicitly required fields are there and follow the rules we have set. Ignoring errors from other packages is a dangerous path to go down

**Comment by dane-johnson** [comment]
The error is just a string, and we don't want the client to see that string. The error message returned by the validation fields is far more descriptive.

**Comment by thebho** [comment]
When I'm troubleshooting a bug I want to see what threw the error and explicitly know if this a JSON format problem or if my request was lacking the "skilldirectory" requirements.  How you handle the response message isn't as important to me as ignoring an error from another package that should be caught and logged

**Comment by dane-johnson** [comment]
https://github.com/maryvilledev/skilldirectory/blob/master/handler/handler.go#L83-L84
Here it seems like we are logging and then sending the client the error. Would it be a good idea to decouple these? Is that really what's happening?

**Comment by thebho** [comment]
I think that is fine.  If there are specific times we don't want the user to get the error message we should catch that error, log it, and then pass a custom message up to the handler.

**Comment by dane-johnson** [comment]
So we need to move error logging into the controllers?

**Comment by thebho** [comment]
Only when an error is being ignored.  I think this situation would fail to compile in Java.  You either have to catch the exception and handle it or pass it up.  We would be doing neither with these changes

**Comment by dane-johnson** [comment]
So you'd prefer something like

	err := json.Unmarshal(body, &skill)
	if err != nil {
		somehow.log(err)
	}

**Comment by thebho** [comment]
c.Warn(), but yeah

**Review by thebho — APPROVED** [review]

**Pull request merged**
