### PR TITLE
Issue91

### LINKED ISSUE #91: Add test coverage gates to the Circle build
Add a 80% gate to builds
https://blog.golang.org/cover

### PR DESCRIPTION
**Pull request by dane-johnson**
Closes #91

### CODE REVIEW

**Comment by thebho** [comment]
I saw that this build passed in circle, but we are less than 80% coverage on all those packages.  Can you explain what is supposed to happen in the test script and if there are any workarounds you are using to get <80% coverage to work.

**Comment by dane-johnson** [comment]
Sure, and I'll add all this information to the wiki.
The `-a` flag selects all modules for both correctness and coverage testing.
The `-m` selects a specific module for testing
The `--whitelist` tag means that all modules listed after it will be subjected to correctness tests only, and will be skipped in coverage testing.
There is also a `-t | --threshold` tag that can change the level of coverage required, and the default is 80%.

**Comment by thebho** [comment]
And which packages are you currently whitelisting?

**Comment by dane-johnson** [comment]
`./test -a --whitelist -m ./controller -m ./data -m ./model -m ./util`

**Comment by dane-johnson** [comment]
So basically all of them.

**Review by thebho — APPROVED** [review]
Great, now let's get that coverage up!

**Pull request merged**
